Feature/메인페이지 헤더
KEEPER31337/Homepage-Back pull request #102
Opened 2022-02-05 15:26 UTC by woo-chang

2022-02-05 21:27 UTC, gusah009 requested changes

2022-02-05 21:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
> +  private List<CategoryEntity> children = new ArrayList<>();
@woo-chang 여기에 `CascadeType.ALL`을 준 이유가 있나요?

2022-02-05 21:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/posting/CategoryService.java
> +    return categories.stream().map(CategoryResult::new).collect(Collectors.toList());
👍👍👍👍

2022-02-05 21:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
> +@Setter
@woo-chang Entity는 불변성을 유지해야 하는데, `@Setter`를 전체에 주신 이유가 있나요? `id`값이 바뀌면 불변성을 해치지 않을까요?

2022-02-05 21:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/dto/result/CategoryResult.java
> +  public CategoryResult(CategoryEntity category) {
@woo-chang `dto`와 `Entity`를 분리한 작업은 너무 훌륭한 것 같습니다. 저도 보고 배워야겠습니다.

2022-02-06 13:27 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
> +  private List<CategoryEntity> children = new ArrayList<>();
부모 엔티티와 연관 되어 동작해야 한다 생각했었는데 필요 없을 것 같습니다. 수정하겠습니다!

2022-02-06 13:30 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/posting/CategoryEntity.java
> +@Setter
당연히 `@Setter`가 존재하면 안되는 코드입니다...

2022-02-07 01:55 UTC, gusah009 approved these changes
👍👍👍

2022-02-07 04:32 UTC, koty08 reviewed
👍

2022-02-07 12:32 UTC, merged