Feature/다른회원관리 정보조회
KEEPER31337/Homepage-Back pull request #109
Opened 2022-02-08 11:29 UTC by woo-chang

close : #60

2022-02-08 14:43 UTC, gusah009 requested changes
@woo-chang 혹시 API 문서는..?

2022-02-09 01:47 UTC, woo-chang commented
> @woo-chang 혹시 API 문서는..?

채원님이랑 문서 엉킬까봐 기능 개발 끝나고 한번에 정리하기로 했는데 괜찮을까 ... ?

2022-02-09 02:27 UTC, gusah009 commented
@woo-chang  병합하겠습니다~ develop 브랜치랑 충돌 해결해서 커밋해주세여!

2022-02-09 02:42 UTC, gusah009 approved these changes

2022-02-09 02:43 UTC, merged