Feature/선택한 도서 정보 전달
KEEPER31337/Homepage-Back pull request #116
Opened 2022-02-09 12:42 UTC by 1004-head

close : #47

2022-02-09 13:06 UTC, gusah009 requested changes

2022-02-09 13:06 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
> +                fieldWithPath("registerDate").description("등록된 날짜")
@1004-head 뭔가 빠졌다 했더니 `bookEntity`에 `thumbnail` 관련 정보가 빠져있었네? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-02-09 13:07 UTC, 1004-head commented on src/test/java/keeper/project/homepage/controller/library/LibraryMainControllerTest.java
> +                fieldWithPath("registerDate").description("등록된 날짜")
그거는 thumbnail 설정하는 브랜치를 따로 파서 한번에 처리하려구요..ㅎㅎ issue 만들어뒀습니다

2022-02-10 07:39 UTC, redundant4u approved these changes

2022-02-10 13:47 UTC, merged