Feature/도서 반납 로직 수정
KEEPER31337/Homepage-Back pull request #130
Opened 2022-02-11 14:32 UTC by 1004-head

close : #129

2022-02-11 22:33 UTC, gusah009 requested changes

2022-02-11 22:33 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookNotFoundException("책이 존재하지 않습니다.");
@1004-head 이건 책이 존재하지 않는 거야 빌린 내역이 존재하지 않는 거야?

2022-02-11 22:33 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookOverTheMaxException("수량 초과입니다.");
@1004-head 만약에 2권, 1권  이렇게 빌려갔을 때 3권을 반납하면 수량초과가 뜰 것 같은데?

2022-02-12 08:00 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookNotFoundException("책이 존재하지 않습니다.");
빌린 내역이 존재하지 않는 경우입니다

2022-02-12 11:31 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookOverTheMaxException("수량 초과입니다.");
로직 수정했습니다

2022-02-12 12:47 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookNotFoundException("책이 존재하지 않습니다.");
에러 메시지는 책이 존재하지 않습니다로 돼 있눈데?

2022-02-12 12:53 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookNotFoundException("책이 존재하지 않습니다.");
무지성 복붙하다가 딸려 왔나봐요... 체크 못 했네요ㅠ

2022-02-12 12:56 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/library/BookManageService.java
>        throw new CustomBookNotFoundException("책이 존재하지 않습니다.");
그러고 보니 반납하려는 책이 없는 경우도 추가해서 만들어야겠네요

2022-02-12 14:06 UTC, shasuri approved these changes

2022-02-12 14:06 UTC, shasuri commented on src/main/java/keeper/project/homepage/repository/library/BookBorrowRepository.java
> +  List<BookBorrowEntity> findByBookAndMemberOrderByBorrowDateAsc(BookEntity book, MemberEntity member);
메소드명 👍👍👍

2022-02-13 09:54 UTC, gusah009 approved these changes

2022-02-13 11:56 UTC, gusah009 commented
프론트에 전달할 사항은 따로 없는거지?

2022-02-13 12:39 UTC, 1004-head commented
> 프론트에 전달할 사항은 따로 없는거지?

네 따로 전달 사항은 없습니다

2022-02-13 22:14 UTC, merged