Feature/내정보관리 포인트관리
KEEPER31337/Homepage-Back pull request #142
Opened 2022-02-14 10:34 UTC by woo-chang

close : #59 

**프론트팀 전달사항**
- 포인트 로그를 생성하는 API는 존재하지 않습니다.
- 받은 포인트 로그/보낸 포인트 로그 결과에서 memberName은 항상 보낸 사람, presentedMemberName은 항상 받는 사람으로 고정

**병합 O**

2022-02-14 11:09 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/point/PointLogController.java
> +  public SingleResult<PointGiftLogResult> transferPoing(
@woo-chang Poing~

2022-02-15 00:47 UTC, gusah009 requested changes

2022-02-15 00:47 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/point/PointLogController.java
> +      @RequestBody PointLogRequest pointLogRequest
@woo-chang 근데 포인트로그 저장을 프론트에서 보내주나요? 백엔드에서 처리해야할 부분 아닌가? 내가 잘 못 이해하고 있는건가

2022-02-15 00:47 UTC, gusah009 commented on src/main/java/keeper/project/homepage/dto/request/PointLogRequest.java
> +        .member(member)
@woo-chang `private MemberEntity member` 인자가 안보이는데 에러 안났나?

2022-02-15 04:36 UTC, woo-chang commented on src/main/java/keeper/project/homepage/controller/point/PointLogController.java
> +      @RequestBody PointLogRequest pointLogRequest
복권 같은거 할 때 당첨금 수령 버튼 누르면 백엔드로 요청이 들어오는거 아닌가 ? 내가 잘못 이해하고 있는걸 수도

2022-02-15 04:38 UTC, woo-chang commented on src/main/java/keeper/project/homepage/dto/request/PointLogRequest.java
> +        .member(member)
Entity가 아니라 API 요청 시 벡엔드에서 전달받는 Dto!

2022-02-15 10:23 UTC, gusah009 commented on src/main/java/keeper/project/homepage/dto/request/PointLogRequest.java
> +        .member(member)
아하~ 👍👍👍

2022-02-15 10:24 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/point/PointLogController.java
> +      @RequestBody PointLogRequest pointLogRequest
아하 게임 로직은 프론트에 맡기면 강제로 포인트를 조절하는 위험이 있어서 백엔드단에서 모두 관리해! 그래서 게임 시작 요청과 동시에 우린 결과만 알려주는 형식이라, 게임 시작 요청이 들어오면 바로 포인트 저장 로직이 실행이 돼.

2022-02-15 14:42 UTC, gusah009 approved these changes
aaa

2022-02-18 07:50 UTC, noonmap approved these changes
👏👏

2022-02-18 07:50 UTC, noonmap commented on src/test/java/keeper/project/homepage/controller/point/PointLogControllerTest.java
> +    memberEntity2 = generateTestMember();
👍👍

2022-02-18 14:24 UTC, gusah009 approved these changes

2022-02-18 14:38 UTC, merged