fix : PostingEntity 반환해주는 부분 총 갯수 반환하도록 수정
KEEPER31337/Homepage-Back pull request #153
Opened 2022-02-17 13:31 UTC by koty08

- 검색, 최신글, 카테고리별 글은 그 자체 size 설정
- 글 하나 가져오기는 size = 1로 return

2022-02-17 13:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
> +  private Integer size;
@koty08 Posting부분도 언젠간 dto 분리 해야할 듯 ... !

2022-02-17 13:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
> +  public void setSize(Integer size) {
@koty08 이런거 그냥 `@Setter` 써도 될 듯 ㅋㅋㅋㅋㅋ

2022-02-17 13:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/posting/PostingService.java
> +      postingEntity.setSize(postingEntities.size());
이런건 어떻게 할 지 한번 생각해봐야겠네 불필요한 연산이 너무 많긴 하다

2022-02-17 13:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/posting/PostingService.java
> +    setSizeInfo(postingEntities);
@koty08 Pageable하게 가져와도 문제없이 개수가 반환되나? 딱 10개만 가져오는거 아니야?

2022-02-18 00:53 UTC, gusah009 requested changes

2022-02-18 00:53 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/posting/PostingService.java
> +    setSizeInfo(postingEntities);
@koty08 그럴 것 같더라 이거 size는 부른만큼 가져와 총 개수 안가져오고 Page 객체로 받아오면 `getTotalPages()` 랑 `getTotalEelments()` 제공해줌!

2022-02-18 04:17 UTC, koty08 commented on src/main/java/keeper/project/homepage/entity/posting/PostingEntity.java
> +  private Integer size;
넵!

2022-02-18 04:48 UTC, koty08 commented on src/main/java/keeper/project/homepage/service/posting/PostingService.java
> +    setSizeInfo(postingEntities);
넵넵

2022-02-18 07:16 UTC, koty08 commented on src/main/java/keeper/project/homepage/service/posting/PostingService.java
> +      postingEntity.setSize(postingEntities.size());
👌

2022-02-18 14:39 UTC, merged