Feature/페이지블럭 썸네일추가
KEEPER31337/Homepage-Back pull request #178
Opened 2022-02-23 14:50 UTC by woo-chang

**프론트팀 전달사항**
- admin, user 로직 분리 완료
- 페이지 블럭 타이틀, 서브타이틀, 컨텐츠 생성 시
/v1/about/title/new => /v1/about/title/create로 변경
- 요청하신 썸네일 추가할 수 있도록 로직 변경

2022-03-08 14:45 UTC, noonmap approved these changes
👍👍 수고하셨습니다

2022-03-08 14:45 UTC, noonmap commented on src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutContentControllerTest.java
> +    thumbnailRepository.save(thumbnailEntity);
`ApiControllerTestHelper` 에 fileEntity와 thumbnailEntity를 생성하는 함수를 사용하는 것도 좋을 것 같습니다.

2022-03-08 14:45 UTC, noonmap commented on src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutContentControllerTest.java
> +                fieldWithPath("data.displayOrder").description("생성에 성공한 페이지 블럭 컨텐츠가 보여지는 순서")
선택사항이지만, 중복되는 field들을 묶어서 정리하면 테스트 코드가 비교적 깔끔해져서 괜찮더라구요.

2022-03-08 14:45 UTC, noonmap commented on src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutSubtitleControllerTest.java
> +    createImageForTest(aftUpdateImage);
`ApiControllerTestHelper`의 `generateThumbnailEntity()` 를 호출하면 썸네일 만드는 데 필요한 fileEntity, image file, thumbnail file, thumbnailEntity가 함께 생성이 되도록 묶어두었습니다.
이걸 활용해보시는 것도 좋을 것 같습니다.

2022-03-08 14:46 UTC, noonmap commented on src/main/java/keeper/project/homepage/admin/controller/about/AdminAboutSubtitleController.java
> +      produces = {MediaType.APPLICATION_JSON_VALUE})
👍

2022-03-09 05:00 UTC, woo-chang commented on src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutContentControllerTest.java
> +    thumbnailRepository.save(thumbnailEntity);
테스트 코드 수정 시 반영하겠습니다

2022-03-09 05:01 UTC, woo-chang commented on src/test/java/keeper/project/homepage/admin/controller/about/AdminAboutContentControllerTest.java
> +                fieldWithPath("data.displayOrder").description("생성에 성공한 페이지 블럭 컨텐츠가 보여지는 순서")
`ApiControllerTestHelper` 코드 확인했어요. 고생하신 흔적이 .. 👍

2022-03-09 11:18 UTC, gusah009 requested changes

2022-03-09 11:18 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/controller/about/AdminAboutContentController.java
> +  @PostMapping(value = "/create")
@woo-chang REST API적으로 봤을 때 해당 url이 행위를 포함하지 않고 있다고 볼 수 있을까?

2022-03-09 11:18 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/controller/about/AdminAboutTitleController.java
>    @DeleteMapping(value = "/delete/{id}")
@woo-chang 여기도 행위를 포함하지 않고 있다고 볼 수 있을까?

2022-03-09 11:18 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/about/AdminAboutTitleService.java
> +  private StaticWriteTitleEntity checkValidTitleId(Long id) {
@woo-chang 함수명을 지을 때 나는 return값을 생각하면서 짓거든. is로 시작하면 bool을 return, get으로 시작하면 해당 resource를 return. check는 어떤 게 유효한 지 확인하는 거라고 생각해서, check로 시작하면 void를 return 하는 데 이건 맞추는 게 좋을까?

2022-03-09 11:43 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/controller/about/AdminAboutContentController.java
> +  @PostMapping(value = "/create")
수정이 필요한 부분인거 같습니다

2022-03-09 11:47 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/about/AdminAboutTitleService.java
> +  private StaticWriteTitleEntity checkValidTitleId(Long id) {
위에서 말한 것처럼 함수명도 정해진 규칙이 있으면 리뷰하기도 좋고 함수명 작성하기도 좋은 거 같은데 의논이 필요해 보일듯 ?

2022-03-10 13:50 UTC, merged