fix : 도서관 오류 수정
KEEPER31337/Homepage-Back pull request #182
Opened 2022-02-25 05:54 UTC by 1004-head

삭제, 대여, 반납에서 bookEntity의 수량을 업데이트 하며 발생한 중복 컬럼 생성 오류

issue : #180

2022-03-09 10:50 UTC, gusah009 requested changes

2022-03-09 10:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
> +    BookEntity updateBookEntity = bookRepository.findByTitleAndAuthor(title, author).get();
@1004-head 여기만 적용되는 건 아니긴 한데, 항상 `.get()`으로 데이터를 불러오기 전에 `isEmpty()`로 null 인지 확인하거나, `Optional<>`을 안 주고,  `orElseThrow()`로 에러를 컨트롤 하는 게 좋아. 위에처럼 에러를 발생시키면 `NullPointException`이 터져서 어디서 에러가 터졌는 지 가늠하기 어렵게 돼.

다른 곳도 이렇게 불러오는 곳이 있으면 수정해보자

2022-03-09 10:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
> +    bookRepository.save(updateBookEntity);
@1004-head 아주 훌륭하구만 👍👍👍👍

2022-03-09 10:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
> +    nowBookEntity.setEnable(enable + quantity);
@1004-head 위에는 `nowBorrow`로 변수명을 썼으면서 여긴 그냥 `borrow`, `enable`이네?

2022-03-11 01:54 UTC, 1004-head commented on src/main/java/keeper/project/homepage/admin/service/library/BookManageService.java
> +    nowBookEntity.setEnable(enable + quantity);
그러게요 대여는 `nowBorrow`로 하고 반납에서는 `borrow`로 썼네요 `nowBorrow`로 통일하겠습니다

2022-03-11 11:32 UTC, koty08 approved these changes

2022-03-11 11:50 UTC, merged