Feature/도서 등록삭제 기능 추가
KEEPER31337/Homepage-Back pull request #19
Opened 2022-01-18 12:45 UTC by 1004-head

2022-01-20 06:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/BookManageService.java
>      return true;
아이고 [여기](https://enormous-button-c5d.notion.site/921c1d8f25d940a594c686b7cf65b821)들어가서 3번 **매크로** 설정 해야겠다 기능 추가하는데 포매팅이 다 바껴서 멀 봐야할 지 어렵네 ㅋㅌㅋㅋㅋㅋㅋㅋ

2022-01-20 06:37 UTC, gusah009 commented on src/main/java/keeper/project/homepage/repository/BookRepository.java
>    Optional<BookEntity> findByTitle(String title);
왜 `@Repository`를 넣는 수정을 하셨나요?

2022-01-20 06:46 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/BookManageService.java
> +    if (quantity + nowTotal > 4) { //동일한 책은 최대 4권까지 가능
4의 의미를 주석으로 처리하는 것도 좋은데, 그것보다 `MAXIMUM_ALLOWD_BOOK_NUMBER` 이런식으로 상수화 하는것도 좋아보임

2022-01-20 07:33 UTC, 1004-head commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +      }
기본적으로 total을 0으로 두고 책이 없으면 quantity를 받아 추가하고 책이 있으면 total을 설정해서 새로 업데이트를 하는 코드라서 저걸 묶어서 쓰게 되면 새로운 책을 추가할 때 문제가 생기게 됩니다 isNotMax함수를 잘못 설계한 것 같아 이 부분은 다시 수정해보겠습니다

2022-01-20 07:37 UTC, 1004-head commented on src/main/java/keeper/project/homepage/repository/BookRepository.java
>    Optional<BookEntity> findByTitle(String title);
혹시 모를 annotation 인식 오류를 예방하기 위해 추가했습니다

2022-01-20 07:40 UTC, 1004-head commented on src/main/java/keeper/project/homepage/entity/BookEntity.java
> +  @Column(name = "picture", unique = true, length = 512)
왜 했는지 모르겠습니다 다시 보니 없어도 될 것 같네요

2022-01-20 08:56 UTC, gusah009 commented on src/main/java/keeper/project/homepage/repository/BookRepository.java
>    Optional<BookEntity> findByTitle(String title);
`JpaRespository`를 상속받는 경우 `@Repository` 어노테이션이 필요없을수도 있습니다. 한번 찾아보시구 말해주세용

2022-01-20 10:52 UTC, shasuri commented on src/main/java/keeper/project/homepage/entity/BookEntity.java
> +  @Column(name = "picture", length = 512)
아이고... 이제 db가 picture 컬럼이 이제 thumbnail_id(int)를 참조하도록 바뀌었습니다.
DB가 자주 바뀔수있으니 이렇게 DB랑 밀접한건 당장 수정 안하시고 한 번에 하셔두 될 것 같아요!

2022-01-20 11:37 UTC, shasuri commented on src/main/java/keeper/project/homepage/service/BookManageService.java
>      if (bookRepository.findByTitle(title).isPresent()) {
`findByTitle()`로 책을 구분해서 찾는 경우가 많던데, 혹시 작가가 다르고 제목이 같은 경우도 생각해두셨나요?

2022-01-20 11:57 UTC, shasuri commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +    Long total = bookManageService.isCanAdd(title, quantity);
`isCanAdd()`메소드를 조금 봤는데 해당 addbook api는 도서관에 책이 이미 있을 때, 책 갯수를 늘리는 경우도 대비한 건가요?
그렇다면 이미 누군가 책을 빌린 상태일 수 도 있으니 경우를 나눠서 UPDATE하는 경우도 추가해야 할 것 같습니다.

2022-01-20 13:05 UTC, gusah009 requested changes

2022-01-20 13:05 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +        Long borrow = bookRepository.findByTitle(title).get().getBorrow();
삭제 로직을 `Controller`보단 Service에 따로 빼는 리팩토링이 필요해 보입니다.

2022-01-20 13:05 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +                .total(quantity)
`@Request Parameter`로 삭제할 수량을 넘겨주는거 아니었나요? total에 삭제할 수량이 들어가는 것 같아서 질문드립니다. 그리고 삭제할 때 삭제 권 수는 total에서 삭제하나요, enable에서 삭제하나요?

2022-01-20 13:05 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/BookManageService.java
>      if (bookRepository.findByTitle(title).isPresent()) {
와 그건 생각 못 했네요 그 경우도 추가하겠습니다

2022-01-20 13:18 UTC, 1004-head commented on src/main/java/keeper/project/homepage/repository/BookRepository.java
>    Optional<BookEntity> findByTitle(String title);
오 맞네요 `JpaRepository`를 상속 받으면 spring이 객체를 알아서 만들고 예외를 jdbc에서 처리해 주네요 있어도 문제는 안 생긴다는데 중복될 필요가 없으니 `@Repository`는 없어도 될 것 같습니다

2022-01-20 13:21 UTC, 1004-head commented on src/main/java/keeper/project/homepage/entity/BookEntity.java
> +  @Column(name = "picture", length = 512)
넵 DB 완전 최종 진짜 최종 나오면 그때 확실히 수정하겠습니다

2022-01-20 13:37 UTC, 1004-head commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +                .total(quantity)
삭제 할 수량을 뺀 값을 넣었어야 하는데 실수했습니다 삭제 권 수는 total과 enable에서 둘 다 삭제합니다

2022-01-20 18:07 UTC, gusah009 requested changes

2022-01-20 18:07 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +        bookManageService.updateDeleteInformation(title, quantity);
삭제 가능한 수량을 total 기준으로 잡는 것 같은데,
만약에 삭제권수가 3권 왔고 토탈은 4권인데, 4권 다 빌려갔으면 enable은 -3권이 되고 있는 것 같습니다. 제가 잘못 이해하고 있는거라면 댓글로 설명 부탁드리겠습니다.

2022-01-21 04:54 UTC, 1004-head commented on src/main/java/keeper/project/homepage/controller/BookController.java
> +        bookManageService.updateDeleteInformation(title, quantity);
제대로 이해하신 것 같습니다 삭제 수량 기준을 enable로 잡도록 수정 해야 할 것 같습니다

2022-01-22 07:24 UTC, gusah009 approved these changes

2022-01-22 09:26 UTC, shasuri commented on src/main/java/keeper/project/homepage/controller/BookController.java
>      if (bookManageService.isCanDelete(title, quantity)) {
`isCanDelete` 메소드명을 좀 더 직관적으로 `isExist` 등으로 바꾸는 건 어떨까요? 다른 의도가 있거나 특별한 이유가 있으면 안바꿔도 될 것같습니다.

2022-01-22 11:20 UTC, 1004-head commented on src/main/java/keeper/project/homepage/controller/BookController.java
>      if (bookManageService.isCanDelete(title, quantity)) {
원래 삭제 가능한지 판단 조건을 다 저 함수에서 처리하려 했는데 만들고 보니 isExist로 하는게 더 나을 것 같아 보입니다

2022-01-22 12:09 UTC, 1004-head commented on src/main/java/keeper/project/homepage/service/BookManageService.java
>      if (bookRepository.findByTitle(title).isPresent()) {
추가했습니다

2022-01-24 04:27 UTC, redundant4u approved these changes

2022-01-24 13:44 UTC, merged