Feature/게시판 crud
KEEPER31337/Homepage-Back pull request #22
Opened 2022-01-21 01:35 UTC by noonmap

- 게시판 CRUD
- 댓글 CRUD

2022-01-22 03:39 UTC, gusah009 requested changes

2022-01-22 03:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +        : responseService.getSingleResult("fail to update");
@noonmap 여기 받아온 `result`의 `commentId`가 바뀔 일이 있나? `update`했을 때 실패하면 `null`을 반환하는걸 이용해서 (null을 반환 안할 수도 있음 잘 모름) `NullException`이나 그냥 `Exception` 처리를 하는건 어때? 
그리고 방금 getSingleResult함수안에 들여다 봤는데, 성공코드를 return 하게 돼있어. 이 부분도 생각해보면 좋을 듯

2022-01-22 03:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/exception/CustomCommentNotFoundException.java
> +public class CustomCommentNotFoundException extends RuntimeException {
@noonmap `/exception/ExceptionAdvice`안에 해당 에러가 일어났을 때 행동을 정의할 수 있습니다. 추가하셔서 사용하면 좋을 것 같아요

2022-01-22 03:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/CommentService.java
> +}
다 잘 만드신거 같아여 👍👍👍

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
> +            pathParameters(
@noonmap PathParameter 정보가 API 문서에 없는 것 같습니다.

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
> +                fieldWithPath("list[].parentId").description("대댓글인 경우, 부모 댓글의 id"),
@noonmap 대댓글이 아닌 경우 default 값이 어떤 게 들어가나요?

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
> +}
@noonmap 각 Tests에 성공시, 실패시, 아니면 다른 어떤 분기에 대한 테스트는 없고 모두 성공했을 경우만 Test하고 있는 것 처럼 보입니다. 각 경우의 수 마다 Test를 작성해야 올바른 작성이 될 것 같아요

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/repository/CommentRepositoryTest.java
> +  }
@noonmap 이건 어떤걸 Test하고 있는 건가요..?

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/repository/CommentRepositoryTest.java
> +    commentRepository.findAll().forEach(comment -> LOGGER.info(comment.getId()));
@noonmap list 개수가 올바르게 나오는지, 확인하는 Test를 작성해 보는것도 좋아보입니다.

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/repository/CommentRepositoryTest.java
> +}
@noonmap 여러개의 데이터를 넣어서 Pageable이 잘 동작하는지도 확인하는 테스트가 있으면 좋을 것 같습니다

2022-01-22 03:39 UTC, gusah009 commented on src/test/java/keeper/project/homepage/service/CommentServiceTest.java
> +    commentRepository.save(commentEntity); // db에 comment가 없는 경우 대비
@noonmap 각각의 `commentRepository.save(commentEntity);`들이 공통이라면 `@BeforeEach`에 넣는 건 어떤가요?

2022-01-22 07:15 UTC, gusah009 requested changes
@koty08 깔게없다...

2022-01-22 07:15 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/FileService.java
> +        filePath = filePath + "\\" + fileName;
@koty08 `filePath`에 들어가는 파일경로 + 파일명에 **파일명** 부분은 파일명 중복을 피해야 해서 진짜 파일명이 아니라 파일명 + 타임스탬프(Nano Second 단위까지) 해야할 것 같어.
[TimeStamp nanosecond 구하기](https://wakestand.tistory.com/396)

2022-01-22 07:15 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/FileService.java
> +        filePath = filePath + "\\" + fileName;
파일명 중복을 피했으면 이제 보안을 생각해 봐야해. `@이창율` 말에 따르면 http://coashanee5.blogspot.com/2017/04/blog-post_5.html?m=1
이 링크에서 나온 것 처럼 보안 취약점이 있대. 그래서 **파일명 + 타임스탬프**로 각 파일을 구분한걸 `SHA-256`으로 해쉬해서 파일명을 만드는 게 좋을 것 같아.
밑에 이미지처럼 `SHA-256`은 왠만하면 안겹친다고 생각해도 될 것 같애
https://files.slack.com/files-pri/T02RUSVHKKN-F02UDHWFH4J/image.png

2022-01-23 03:19 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +  private CommentService commentService;
`@RequiredArgsConstructor`가 있으면 `final`이나 `@NotNull`이 붙어있는 필드를 자동으로 생성해준다고 합니다. `@Autowired` 없는 방향으로 수정하겠습니다!

2022-01-23 03:20 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +  private final ResponseService responseService;
22

2022-01-23 03:21 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +    Optional<PostingEntity> postingEntity = postingRepository.findById(postId);
보고 많이 놀라셨죠? 저도 많이 놀랐습니다 바로 수정하겠습니다!

2022-01-23 03:21 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +      return responseService.getSingleResult("postingId not found");
수정하겠습니다!

2022-01-23 03:24 UTC, noonmap commented on src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
> +                fieldWithPath("list[].parentId").description("대댓글인 경우, 부모 댓글의 id"),
default로 자신의 id가 들어가도록 수정하겠습니다

2022-01-23 03:31 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +        : responseService.getSingleResult("fail to update");
null로 하도록 수정하겠습니다!

2022-01-23 03:32 UTC, koty08 commented on src/main/java/keeper/project/homepage/entity/PostingEntity.java
> +  @ManyToOne(targetEntity = MemberEntity.class, fetch = FetchType.LAZY)
Mapping 관계에서 어느쪽에서 EAGER을 사용할지 고민이었는데, 확실히 Member-Posting 관계에서는 LAZY보다는 EAGER이 좋을것 같네요

2022-01-23 03:33 UTC, koty08 commented on src/main/java/keeper/project/homepage/controller/PostingController.java
> +    }
넵 수정하도록 하겠습니다

2022-01-23 03:34 UTC, koty08 commented on src/main/java/keeper/project/homepage/entity/PostingEntity.java
> +    this.writer = null;
:clap:

2022-01-23 07:37 UTC, noonmap commented on src/main/java/keeper/project/homepage/controller/CommentController.java
> +  private CommentService commentService;
> @noonmap `@RequiredArgsConstructor` 어노테이션이 있으면 `@Autowired` 안붙여도 알아서 주입될걸? 찾아보고 말점

@RequiredArgsConstructor가 있으면 final이나 @NotNull이 붙어있는 필드를 자동으로 생성해준다고 합니다. @Autowired 없는 방향으로 수정하겠습니다!

2022-01-24 05:39 UTC, noonmap commented on src/main/java/keeper/project/homepage/exception/CustomCommentNotFoundException.java
> +public class CustomCommentNotFoundException extends RuntimeException {
@gusah009 exception, test는 곧 수정하겠습니다.!

2022-01-24 07:42 UTC, noonmap commented on src/test/java/keeper/project/homepage/controller/CommentControllerTest.java
> +                fieldWithPath("list[].parentId").description("대댓글인 경우, 부모 댓글의 id"),
@gusah009 이미 디비에는 모댓글인 경우 parent_id에 0이 들어가게 되어있다고 합니다. default는 0으로 들어가도록 수정하겠습니다!

2022-01-24 13:40 UTC, merged