Feature/#266 member api 요청
KEEPER31337/Homepage-Back pull request #272
Opened 2022-05-03 13:50 UTC by woo-chang

## 연관 issue
close: #266

## 프론트 전달사항
- /v1/members/multi?ids=1,2,3 같이 멤버 리스트 ID를 콤마로 구분하여 파라미터로 전송합니다.
- 멤버 ID가 정상적으로 존재하는 경우 해당 멤버에 알맞은 데이터가 전달됩니다.
- 멤버 ID 리스트 중 멤버 ID가 존재하지 않거나 가상의 멤버에 접근하는 경우 API 요구사항에 따라 API 요청 실패 처리가 되는 것이 아닌 실패 데이터가 추가되고 다른 정상적인 멤버 데이터는 성공적으로 전달됩니다.
- 멤버 ID의 조회 실패에 대한 실패 데이터는 멤버 ID와 실패한 이유를 전송하게 되고 나머지 데이터는 null로 전송됩니다.

2022-05-04 06:15 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
@woo-chang `mapStruct`를 안쓰고 이렇게 dto 변환 함수를 만든 이유가 있을까요? `Entity`입장에서 `Dto`의 존재를 알고 있어야 하는 이유 역시 궁금합니다!

2022-05-04 06:15 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/dto/member/MultiMemberResponseDto.java
> +public class MultiMemberResponseDto {
@woo-chang user단에서 `MemberResponseDto`들 중에 공통적으로 보내는 부분들이 있을 것 같은데, 그 부분들은 부모 클래스로 뽑아서 나중에 새로운 컬럼이 생기거나 했을 때 누구나 볼 수 있는 컬럼이면 부모 클래스만 수정하면 되게끔 하는 것도 괜찮아 보입니다.

2022-05-04 06:15 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/member/MemberService.java
> +            MultiMemberResponseDto.builder().id(id).msg("Fail: Not Exist Member").build());
@woo-chang 뭔가 이뿌네요 👍👍👍

2022-05-04 06:15 UTC, gusah009 commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +  public void getMultiMembersSuccess() throws Exception {
@woo-chang Test 코드에 로직대로 Virtual Member는 잘 거르는지, 존재하지 않는 Member는 잘 거르는지, 메시지는 잘 나오는지 확인해봐도 좋을 것 같습니다.

2022-05-04 07:04 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
https://www.inflearn.com/questions/15292

2022-05-04 07:04 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
https://www.inflearn.com/questions/15292

2022-05-04 07:13 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
**MapStruct 사용하지 않은 이유**
- `MapStruct`에 대해 고민해보았는데 모든 DTO에 대해 각각의 MapStruct가 필요하게 되고 복잡해질 시 유연성도 떨어진다는 단점이 더 크게 다가왔던 것 같습니다.
- 참고 : https://www.inflearn.com/questions/15292


**Entity, Dto 주체**
- 요청이 들어왔을 때 : `ResquestDto` -> `Entity`로의 변환이 주를 이루기 때문에 `Dto` 입장에서 `Entity`로 변환될 책임이 존재하고 Entity 존재 여부를 알아야 한다고 생각이 들었고
- 응답을 보낼 때 : `Entity` -> `ResponseDto`로의 변환이 주를 이루기 때문에 `Entity`입장에서 `Dto`로 변환될 책임이 존재하고 Dto 존재 여부를 알아야 한다는 생각이 들게 되어서 위와 같이 작성했습니다.

2022-05-04 07:14 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
또 추후에 연관있는 Dto는 `Inner Class`로 관리하는 리팩토링 과정을 진행할 예정인데 그 과정에서 MapStruct가 불편할 것 같다는 생각이 들게 되었습니다.

2022-05-04 07:16 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/dto/member/MultiMemberResponseDto.java
> +public class MultiMemberResponseDto {
리팩토링 과정에서 참고하여 진행하겠습니다~

2022-05-04 07:35 UTC, woo-chang commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +  public void getMultiMembersSuccess() throws Exception {
테스트 코드 추가해서 올려뒀습니다~

**질문 사항**
다른 파트 `TDD`로 리팩토링 진행하면서 `Service`단 테스트 코드와 `Controller`단 테스트 코드가 (인증이나 파라미터 추가하는 것 제외) 로직상으로는 대부분 중복되어 나타나는 것을 확인했습니다. Controller에 특별한 로직없이 **Service 결과를 반환하는 정도의 코드**만 존재해서 그렇다고 생각하는데 이 점은 어떻게 진행하면 좋을지 궁금합니다.

2022-05-04 09:16 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/member/MemberEntity.java
> +  public MultiMemberResponseDto toMultiMemberResponseDto() {
위의 `mapstruct`를 안 쓰는 이유 중에 런타임이 돼야 문제를 찾을 수 있다는 게 치명적인 것 같긴 하네용

2022-05-04 09:31 UTC, gusah009 commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +  public void getMultiMembersSuccess() throws Exception {
`Controller`단에서 위와 같이 로직이 단순한건 굉장히 좋은 코드라고 생각합니다. 왜냐면 컨트롤러에선 어떤 입력이 오고 어떤 출력이 나가는지, url은 어떤건지 같은 부분에 집중해야 한다고 생각하기 때문입니다. 어떤 중복 문제가 생기는 지 예시가 있으면 좋을 것 같습니다!

2022-05-04 10:09 UTC, woo-chang commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +  public void getMultiMembersSuccess() throws Exception {
예를 들어 `포인트 선물 로직`을 테스트한다고 했을 때 Service 테스트도 포인트 선물 성공, 실패 테스트를 진행하게 되고 Controller 테스트도 포인트 선물 성공, 실패 테스트를 진행하게 되서 같은 로직에 대한 테스트가 중복된다고 생각했었는데 Service단에서는 `Mock`을 통해 `로직`에 집중하고 Controller단에서는 로직에 집중하기보다는 API의 `url`, `입출력` 등을 테스트한다고 생각하면 중복이라는 말이 잘못 사용된거 같네용

2022-05-04 10:40 UTC, gusah009 requested changes

2022-05-04 10:40 UTC, gusah009 commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +        .andExpect(jsonPath("$.list[0].id").value(3))
@woo-chang 3이란 값은 위험할 것 같습니다. id가 3인 Member가 Test시에 DB에 없다는 보장이 없습니다. 음수나 다른 값을 하는 것도 좋아 보입니다!

2022-05-04 13:16 UTC, woo-chang commented on src/test/java/keeper/project/homepage/user/controller/member/MemberControllerTest.java
> +        .andExpect(jsonPath("$.list[0].id").value(3))
좋은 리뷰~🔥🔥🔥

2022-05-07 08:12 UTC, noonmap approved these changes

2022-05-09 02:21 UTC, merged