Feature/게시판 파일 삭제 로직 수정
KEEPER31337/Homepage-Back pull request #274
Opened 2022-05-05 03:19 UTC by JeonghakLee

## 연관 issue
close: #268 

## 참고 사항
혹시 몰라서 기존 파일 삭제 관련 코드는 그대로 두었습니다. 문제가 없다면 추후 삭제하도록 하겠습니다.

## 프론트 전달사항
기존 GET v1/post/delete/{fileId} 에서 파라미터로 file ID 리스트를 받아 삭제할 수 있도록 변경하였고,
REST API 규칙을 적용해 DELETE v1/post/files?fileIdList=0000,1111,2222 와 같은 형식으로 URI를 변경하였습니다.

2022-05-05 10:32 UTC, woo-chang requested changes
연결된 `issue`의 내용으로는 수정 버튼을 눌렀을 때 파일이 진짜 삭제 되는 것으로 이해했는데 올리신 코드는 해당 의도와 다른 것 같아 설명 한번 부탁드립니다.

2022-05-05 10:52 UTC, JeonghakLee commented
> 연결된 `issue`의 내용으로는 수정 버튼을 눌렀을 때 파일이 진짜 삭제 되는 것으로 이해했는데 올리신 코드는 해당 의도와 다른 것 같아 설명 한번 부탁드립니다.

아 기존에는 삭제할 때 마다 파일 삭제 API를 보내어 수정완료가 되지 않았음에도 해당 파일이 삭제되는 문제가 있었는데 
이를 해결하기 위해서 프론트에서 수정을 완료하기 전 까지 삭제할 파일의 ID들을 저장해 두었다가 수정 버튼을 누를 때 삭제 API를 호출하여 한번에 삭제하도록 수정한 것입니다.

2022-05-05 12:28 UTC, woo-chang requested changes

2022-05-05 12:28 UTC, woo-chang commented on src/main/java/keeper/project/homepage/util/service/FileService.java
> +      deleteFileById(deleteId);
클라이언트의 요청을 무조건적으로 믿을 수 없기에 `default` 이미지나 `뱃지` 이미지 같이 삭제 되면 안되는 파일들에 대한 `예외처리`가 필요해보입니다.

2022-05-06 03:03 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/util/service/FileService.java
> +      deleteFileById(deleteId);
기존에 기본 이미지 삭제 예외를 처리하기 위해 사용하는 DefaultThumbnailInfo라는 코드가 있어서 사용하여 예외 처리를 해두긴 했는데 
해당 코드를 살펴보니  (TODO : 뱃지는 계속 추가됨 -> 뱃지 추가하는 controller & service 만들기) 와 같이 적혀 있어서 
ENUM에 현재 선언? 되어 있는 기본이미지 정보만 존재하여 완전한 예외 처리는 못하는 것 같습니다 이 부분은 공통으로 사용할 코드라 해당 코드 작성자와 추후 논의 후 수정하도록 하겠습니다.

2022-05-06 04:26 UTC, woo-chang commented on src/main/java/keeper/project/homepage/util/service/FileService.java
> +    }
**당장 필요한 수정사항은 아니지만 같이 고민해봤으면 하는 것**
해당 메서드를 보게 되면 파일 ID 리스트를 받아서 하나씩 삭제하는 기능을 수행하는 것은 한번에 알아볼 수 있지만 유효성 검사를 하는지는 하위 메서드로 가서 확인할 수 있었습니다.
따라서 `deleteFileById`에는 `삭제 기능` 뿐더러 `유효성 체크 기능`까지 포함되어 있고 메서드의 복잡성이 증가한 것 같습니다.

```java
public void deleteFilesByIdList(List<Long> fileIdList) {
    for (Long fileId : fileIdList) {
      // 유효성 검사 함수를 통과했을 때 삭제
      if (isDeleteEnable(fileId)) {
        deleteFileById(fileId);
      } else {
        // 예외 처리 코드
      }      
    }
```
기능을 분리하면 위와 같은 코드로 작성이 가능할 것 같은데 어떻게 생각하시는지 궁금하네용
또한 처리할 예외가 추가되더라도 예외 처리코드 수정만 생각할 수 있고 `유지보수`에도 괜찮다는 생각이 들었습니다.

2022-05-06 06:59 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/util/service/FileService.java
> +    }
좋은 의견 감사합니다. 
기존의 파일 ID 하나만 사용해서 삭제를 수행하던 API에 deleteFileById가  사용되고 있었는데 이 코드에서 앞서 말씀해 주신 기본 이미지가 삭제가 가능한 문제가 있었습니다. 그래서 혹시 몰라 남겨둔 기존 API를 그대로 수행하고 예외 처리도 할 수 있게 해당 함수 안에 작성해 두었던 것 인데 바뀐 API로 전환하면 refactoring을 통해서 복잡성을 줄여 기능이 명확히 구분되는 코드로 바꾸도록 하겠습니다!

2022-05-06 07:35 UTC, woo-chang approved these changes

2022-05-06 09:33 UTC, shasuri approved these changes

2022-05-06 12:35 UTC, merged