Feature/253 study 리팩토링&버그수정
KEEPER31337/Homepage-Back pull request #278
Opened 2022-05-09 13:45 UTC by gusah009

## 연관 issue
close #253

## 프론트 전달사항
- 스터디원 수가 2배씩 적용되던 버그를 해결하였습니다.

2022-05-09 14:31 UTC, JeonghakLee requested changes

2022-05-09 14:31 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/user/service/study/StudyService.java
> +    if (isAlreadyStudyMember(studyEntity, memberId)) {
이 부분 혹시 !isAlreadyStudyMember가 맞지 않나요?

2022-05-10 02:24 UTC, JeonghakLee approved these changes

2022-05-10 02:47 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/study/StudyService.java
> +    if (isAlreadyStudyMember(studyEntity, memberId)) {
@JeonghakLee 헐... 그러네요! 감사합니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2022-05-10 06:49 UTC, 1004-head approved these changes

2022-05-10 13:07 UTC, merged