Feature/#298 출석 랭킹 api 수정
KEEPER31337/Homepage-Back pull request #299
Opened 2022-05-24 15:22 UTC by JeonghakLee

## 연관 issue
*close #298*

## 프론트 전달사항
출석 랭킹 API 수정하였습니다.

2022-05-25 01:55 UTC, gusah009 requested changes

2022-05-25 01:55 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/dto/attendance/RankDto.java
> +  public static RankDto toDto(MemberEntity member) {
저랑 같은 방식으로 개발하셨네요! 😀

2022-05-25 01:55 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
> +  private int rank = 1;
이건 field 변수로 지정해 놓으신 이유가 있을까요? `@Service` 어노테이션이 해당 클래스를 싱글턴으로 유지하기 때문에 문제가 생길 수도 있을 것 같습니다. 테스트 시 문제는 없었나요?

2022-05-25 04:18 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
> +  private int rank = 1;
앗 lambda 식에서 effectively final 변수만 사용 가능하다고 해서 그것만 해결 하려고 코드를 작성하다 보니  상태를 가지게 코드를 작성해 버렸네요 수정하도록 하겠습니다..ㅎ

2022-05-25 04:20 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/user/dto/attendance/RankDto.java
> +  public static RankDto toDto(MemberEntity member) {
수정해야할 부분과 비슷한 API를 최근에 작성하셨길래 같이 참고했습니다😀

2022-05-26 00:25 UTC, woo-chang approved these changes

2022-05-26 00:25 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/service/attendance/RankService.java
>      List<MemberEntity> members = memberRepository.findAll(pageable).stream()
@JeonghakLee `stream`을 사용하니 코드도 간결해지고 직관적으로 의미가 다가와서 좋은 것 같습니다. 성능이 극단적으로 필요로 하는 상황이 아니라면 가독성 측면에서 적극적인 사용이 좋아보입니다.

2022-05-26 01:50 UTC, shasuri approved these changes

2022-05-26 03:22 UTC, merged