feat: 세미나 Entity, Repository, Repository Test 구현
KEEPER31337/Homepage-Back pull request #368
Opened 2022-08-18 04:11 UTC by JeonghakLee

## 연관 issue
close#352

2022-08-18 06:26 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
기본으로 들어있는 값들을 관리하는 것 같은데 이렇게 관리하게되면 내용이 바뀌거나 삭제되었을 때 코드의 수정이 일어나야할 것 같다는 생각이 들었습니다. 조금 더 변화에 유연하게 관리할 수 있는 방법이 없을까용?

2022-08-18 06:26 UTC, woo-chang commented on src/test/java/keeper/project/homepage/repository/seminar/SeminarAttendanceRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
`SeminarRepositoryTestHelper`에 사용된 어노테이션을 중복 사용하고 있는 것 같습니다!

2022-08-18 06:26 UTC, woo-chang commented on src/test/java/keeper/project/homepage/repository/seminar/SeminarRepositoryTest.java
> +    SeminarEntity findSeminarEntity = seminarRepository.findByName(seminarEntity.getName());
name이 null일 때 케이스도 존재하면 좋을 것 같습니다

2022-08-18 06:26 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceEntity.java
> +  @PrimaryKeyJoinColumn
`@PrimaryKeyJoinColumn`을 사용하신 이유가 궁금합니다.

2022-08-18 06:26 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceExcuseEntity.java
> +  @JoinColumn(name = "seminar_attendance_id", referencedColumnName = "id")
`PK`가 없는 테이블에 대해 잘 처리하신 것 같습니다 👍🏻👍🏻

2022-08-18 07:19 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceEntity.java
> +  @PrimaryKeyJoinColumn
`SeminarAttendanceExcuseEntity`의 `pk`가 `  `SeminarAttendanceEntity`의 `fk`이자 `pk`인데 이를 지정하기 위해 사용하였습니다!

2022-08-18 07:20 UTC, JeonghakLee commented on src/test/java/keeper/project/homepage/repository/seminar/SeminarRepositoryTest.java
> +    SeminarEntity findSeminarEntity = seminarRepository.findByName(seminarEntity.getName());
추가해 보겠습니👍

2022-08-18 07:20 UTC, JeonghakLee commented on src/test/java/keeper/project/homepage/repository/seminar/SeminarAttendanceRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
앗 수정하겠습니다!

2022-08-18 07:54 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
음... 당장 떠오르는 방법은 status enum을 만들고 entity에 enum을 받아 entity를 생성하는 메서드를 구현하는 방법이 있을 것 같은데 혹시 또 어떤 좋은 방법이 있을까요??

2022-08-18 08:05 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceEntity.java
> +  @ManyToOne
SeminarAttendanceEntity를 조회할 때 항상 status가 사용되기 때문에 사용하지 않았습니다. 
LAZY로 해두고 fetch join을 사용해서 성능 최적화를 하는게 나을까요?

2022-08-18 08:37 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceEntity.java
> +  @ManyToOne
항상 사용된다면 그대로 사용해도 좋을 것 같습니다

2022-08-18 08:40 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
`DB`에 저장되어 있는 값들이니 받아와서 생성하는 방법은 어떨까요?

2022-08-18 08:52 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
해당 값들이 변경될 가능성이 존재하지 않는다면 위 방법도 괜찮을 것 같습니다!

2022-08-18 09:25 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceEntity.java
> +  @ManyToOne
현재에 항상 사용된다고 하더라도 `LAZY`로 설정하는 게 좋을 것 같습니다! 

이후에 `SeminarAttendanceStatusEntity`를 사용하지 않는 곳이 생긴다면 **불필요하게 항상 데이터를 join해서 가져오는 형식**이 되어 버립니다.

2022-08-18 09:39 UTC, gusah009 reviewed
와우... 완전 고생많으셨습니다! 특히 FK랑 PK가 같은 부분에 `@MapsId`라는 어노테이션을 쓸 수 있는 지 몰랐네요. 👍👍

2022-08-18 09:39 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
@woo-chang 님 말대로, DB에서 가져오는 게 좋을 것 같습니다! 출석 상태에 대해 나중에 수정, 삭제, 삽입이 가능하도록 기획이 바뀐다면 해당 코드는 문제가 많이 발생할 것 같습니다.

2022-08-18 10:04 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/entity/seminar/SeminarAttendanceStatusEntity.java
> +
아 이미 DB에 저장되어 있는 값이란걸 인지하지 못했습니다 수정하겠습니다!

2022-08-18 14:00 UTC, woo-chang approved these changes
수고하셨습니다 👍👍👍

2022-08-19 02:04 UTC, gusah009 requested changes

2022-08-19 02:04 UTC, gusah009 commented on src/test/java/keeper/project/homepage/repository/clerk/SeminarAttendanceStatusRepositoryTest.java
> +package keeper.project.homepage.repository.clerk;public class SeminarAttendanceStatusRepositoryTest {
엇 이 파일은 멀까요...?

2022-08-19 02:04 UTC, gusah009 commented on src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
> +  SeminarEntity findByNameIsLike(@NonNull String name);
`findByNameIsLike`로 이름을 통해 세미나를 찾을 경우 겹쳐서 여러개의 세미나가 나올 수도 있고, 세미나가 없을 수도 있을 것 같습니다.

생각나는 해결 방법으로는
1. 이름으로 찾는 걸 포기하거나
2. `List<SeminarEntity>`를 반환하는 게 좋을 것 같습니다.

2022-08-19 02:12 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
> +  SeminarEntity findByNameIsLike(@NonNull String name);
이상적으론 고유한 이름이긴 하지만 설계상 사실 고유하지 않아도 되는 필드이긴하네요 불필요한 것 같아서 삭제하도록 하겠습니다!

2022-08-19 02:13 UTC, JeonghakLee commented on src/test/java/keeper/project/homepage/repository/clerk/SeminarAttendanceStatusRepositoryTest.java
> +package keeper.project.homepage.repository.clerk;public class SeminarAttendanceStatusRepositoryTest {
엇 아마 마지막 커밋에 작성한 테스트 코드의 빈파일이 그전에 섞여 들어간것같습니다 ㅜ

2022-08-19 03:38 UTC, gusah009 approved these changes
고생많으셨습니다! 빠른 피드백 너무 좋았어요!

2022-08-19 03:38 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
> +  private String attendanceCode;
👍👍👍

2022-08-19 03:38 UTC, merged