Feature/세미나 자동출석 api 개발 #359
KEEPER31337/Homepage-Back pull request #388
Opened 2022-08-31 17:30 UTC by shkisme

## 연관 issue

close #359

## 프론트 전달사항
[자동 출석 API - 회장.pdf](https://github.com/KEEPER31337/Homepage-Back/files/9463680/API.-.pdf)
[자동 출석 API - 회원.pdf](https://github.com/KEEPER31337/Homepage-Back/files/9463681/API.-.pdf)

2022-09-01 01:33 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/controller/clerk/AdminAutoAttendanceController.java
> +public class AdminAutoAttendanceController {
`Auto`라는 키워드가 들어가면서 컨트롤러의 역할이 구체화 되버리는 경향이 되는 것 같습니다.

구체화 수준을 조금 낮춰 `AdminAttendanceController`라는 네이밍은 어떨까요?

2022-09-01 01:33 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/controller/clerk/AdminAutoAttendanceController.java
> +@RequestMapping("/v1/admin/clerk/attendance")
`Resources`는 복수 형태가 좋은 것 같습니다.

2022-09-01 01:33 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    SeminarEntity seminar = seminarRepository.findTop1ByOrderByIdDesc().orElseThrow();
`JPA`를 적극적으로 활용하신 점 좋습니다 👍👍

알맞은 예외가 던져지도록 커스터 예외를 생성해서 넣어주어야 할 것 같습니다.

2022-09-01 01:33 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/dto/clerk/response/AttendanceCheckResponseDto.java
> +  public static AttendanceCheckResponseDto from(SeminarAttendanceEntity seminarAttendanceEntity,
정적팩터리 메서드 명명 규칙에 의하면 다음과 같이 나와있습니다.

- **from** : 매개변수를 하나 받아서 해당 타입을 리턴
- **of** : 여러 매개변수를 받아 적합한 타입을 리턴

매개변수가 여러 개인 경우 `of` 사용은 어떨까요?

2022-09-01 01:41 UTC, gusah009 requested changes
조금 더 세심하게 관심을 가지고 개발하면 더 좋을 것 같습니다!

2022-09-01 01:41 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/AutoAttendanceService.java
> +    MemberEntity member = memberUtilService.getById(attendanceCheckRequestDto.getMemberId());
`memberId`를 `request body`로 받아오면 다른 사람이 해당 세미나의 출석을 대신 해줄수도 있지 않을까요?

JWT를 사용하는 게 좋을 것 같습니다

2022-09-01 01:41 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/AutoAttendanceService.java
> +    LocalDateTime attendTime = attendanceCheckRequestDto.getAttendTime();
출석 시간도 서버시간 기준으로 하는 게 좋을 것 같습니다. 이렇게 되면 클라이언트에서 출석 시간을 조작할 수 있을 것 같아요!

2022-09-01 01:41 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/dto/clerk/response/AttendanceCheckResponseDto.java
> +  public static AttendanceCheckResponseDto getInstance(AttendanceCheckOption notCorrect) {
`AttendanceCheckOption` 을 따로 만들어두신 이유가 있으신가요?

2022-09-01 01:41 UTC, gusah009 commented on src/test/java/keeper/project/homepage/admin/controller/clerk/AdminAutoAttendanceControllerTest.java
> +            .build());
`generateSeminar()`로 분리하면 더 좋을 것 같습니다.

2022-09-01 01:41 UTC, gusah009 commented on src/test/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceServiceTest.java
> +    SeminarEntity findLatestSeminar = seminarRepository.findTop1ByOrderByIdDesc().orElseThrow();
서비스 테스트에서 레포지토리 메서드를 테스트하는 이유가 있는 지 궁금합니다!

2022-09-01 01:41 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/clerk/AutoAttendanceSpringTestHelper.java
> +  private static final Integer NO_DEMERIT = 0;
`Service` 코드에서 해당 상수가 똑같이 정의된 걸 확인했는데, `package-private`으로 테스트코드와 상수를 공유하는 건 어떨까요?

2022-09-01 01:41 UTC, gusah009 commented on src/test/java/keeper/project/homepage/user/controller/clerk/AutoAttendanceControllerTest.java
> +            )));
`rest docs`를 제작하는 코드가 겹치는 것 같습니다!

2022-09-01 06:19 UTC, shkisme commented on src/main/java/keeper/project/homepage/admin/controller/clerk/AdminAutoAttendanceController.java
> +public class AdminAutoAttendanceController {
`AdminAttendanceController`로 짓는 것은 상관없는데,
User 쪽 컨트롤러에 이미 `AttendanceController`가 있어서 이렇게 네이밍 했습니다!

2022-09-01 06:28 UTC, shkisme commented on src/main/java/keeper/project/homepage/user/dto/clerk/response/AttendanceCheckResponseDto.java
> +  public static AttendanceCheckResponseDto from(SeminarAttendanceEntity seminarAttendanceEntity,
`of`로 명명하는게 맞겠네요 감사합니다👍

2022-09-01 06:30 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    seminar.setLatenessCloseTime(requestDto.getLatenessCloseTime());
@gusah009 개인사정 결석을 처리하기 위해 세미나를 미리 생성하는 경우가 있기도 하고 상황에 따라 자동 출석은 유동적으로 설정해야 할 것 같긴합니다

2022-09-01 06:35 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    }
이 로직은 다음 세미나를 미리 생성해 둔 경우에 해당 세미나의 출석 전 상태까지 전부 결석처리하게 되지 않을까요?

2022-09-01 06:36 UTC, shkisme commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    seminar.setLatenessCloseTime(requestDto.getLatenessCloseTime());
서기가 개인사정 결석 처리를 위해 세미나를 미리 등록한다고 가정하고 코드를 짜긴 했습니다!

2022-09-01 06:41 UTC, shkisme commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    }
출석이 종료되었을때 이 API를 호출해서 출석 전 상태의 회원을 결석처리하려고 했는데, 좀... 문제가 있는거같네요 더 고민해서 수정해보겠습니다!

2022-09-01 06:43 UTC, shkisme commented on src/main/java/keeper/project/homepage/admin/controller/clerk/AdminAutoAttendanceController.java
> +@Secured("ROLE_회장")
프론트에서 회장만 한다고 전달받긴 했는데 확실히 부회장, 서기에게도 권한을 주는게 상황 대비에 맞는것 같습니다👍

2022-09-01 07:32 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/user/service/clerk/AutoAttendanceService.java
> +      SeminarAttendanceEntity seminarAttendanceEntity, LocalDateTime attendTime) {
출석 상태를 판단하는 역할과 판단한 결과를 처리하는 역할까지 하고 있는데 메서드명만 봐서는 알기 힘든 내용 같습니다. 
그리고 결석시 벌점부여하는 코드가 중복되고 있어서 분리하면 좋을 것 같아요.

2022-09-01 07:34 UTC, JeonghakLee commented on src/test/java/keeper/project/homepage/controller/clerk/AutoAttendanceSpringTestHelper.java
> +  private static final Integer NO_DEMERIT = 0;
이 부분은 추후 상벌점 타입 레포지토리를 활용하면 좋을 것 같습니다!

2022-09-01 07:36 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminAutoAttendanceService.java
> +    }
세미나 id를 이용해 해당 세미나의 출석정보만 가져오면 될 것 같습니다

2022-09-05 02:50 UTC, gusah009 reviewed
이제 저보다 잘하시는 것 같습니다!! 👍👍👍

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +  public void processAttendance(SeminarAttendanceEntity attendance,
여기 주석 `//TODO: Transactional로 설정`은 무슨 의미일까요?

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +        .orElse(SeminarSearchByDateResponseDto.NONE);
`map` 뒤에 `orElse`는 처음보네요! 어떤 조건일 때 `orElse`가 실행되는 건가요?

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
> +  }
`Entity`에서는 `request`를 인자로 받기보다 `attendanceCloseTime`, `latenessCloseTime`를 인자로 받는 게 좋을 것 같습니다!

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +    seminarHostAutoAttendance(seminar);
메서드명 👍👍

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +    schedulerService.scheduleTask(task, date);
여기에서 `notAttendances`는 세미나가 시작할 때 출석이 안된 사람들 아닌가요?

그럼 나중에 시간이 흘러서 task가 실행될 때 출석을 한 사람들도 세미나 불참이 되는 게 아닌가 싶습니다!

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
> +   */
👏👏👏

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
> +      @Param("now") LocalDateTime now);
👏👏

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +        CustomSeminarAttendanceNotFoundException::new);
으아악 포맷팅이 불편합니다!! 😂

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    return status.equals(BEFORE_ATTENDANCE.getType()) && attendanceTime.compareTo(deadline) <= 0;
`attendanceTime`이나 `deadLine`을 `String`으로 변환한 후에 비교하는 이유가 있을까요? 

`LocalDateTime`에 충분히 비교할 수 있는 메서드를 제공하는 것으로 알고 있습니다!

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    if (userAttendanceCode.compareTo(seminar.getAttendanceCode()) != 0) {
`equals`를 사용하지 않고 `compareTo`를 사용한 이유가 있을까요?

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    } else if (attendanceTime.compareTo(latenessDeadLine) <= 0) {
조건문 안에 `compareTo() <= 0`의 의미를 잘 모르겠습니다!

2022-09-05 02:50 UTC, gusah009 commented on src/main/java/keeper/project/homepage/util/service/SchedulerService.java
> +  }
고생 많으셨습니다!! 👍👍

2022-09-05 02:50 UTC, gusah009 commented on src/test/java/keeper/project/homepage/admin/controller/clerk/AdminSeminarControllerTest.java
> +  @DisplayName("[FAIL] 해당 날짜의 세미나 조회 - 형식에 맞지 않은 날짜 입력")
컨트롤러에서 해야 할 테스트를 너무 잘 해주신 것 같습니다!! 👍👍👍

2022-09-05 04:23 UTC, JeonghakLee reviewed
전체적으로 코드가 굉장히 깔끔하고 테스트도 세세하게 잘 작성하신 것 같습니다👏👏👏
특히 예외 처리 부분은 잘 참고해서 제 코드를 리팩토링 해봐야 할 것 같네요!

2022-09-05 04:23 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/util/service/SchedulerService.java
> +  }
👍👍👍👍

2022-09-05 04:23 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/user/dto/clerk/request/AttendanceCheckRequestDto.java
> +  private LocalDateTime attendanceTime;
출석 요청시간을 클라이언트로부터 받으면 조작될 가능성은 없나요?

2022-09-05 04:23 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminMeritService.java
> +     */
그럼 자동 출석 때 상벌점 내역 저장에 실패하는 건가요?

2022-09-05 09:53 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +  public void processAttendance(SeminarAttendanceEntity attendance,
`CUD`가 발생하는 메서드인데 `@Transactional` 어노테이션이 적용되어 있지 않아 적용하였습니다

2022-09-05 09:53 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +        .orElse(SeminarSearchByDateResponseDto.NONE);
받아오는 값이 `Optional`이라 `null` 값인 경우 `map`이 아닌 `orElse`가 실행됩니다!

2022-09-05 09:54 UTC, woo-chang commented on src/main/java/keeper/project/homepage/entity/clerk/SeminarEntity.java
> +  }
메서드 인자를 줄이기위해 고민하다 `request`를 인자로 전달하는 방법을 선택했는데 각각 받아오는 것이 더 명시적인 것 같습니다 👍

2022-09-05 09:56 UTC, gusah009 commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +        .orElse(SeminarSearchByDateResponseDto.NONE);
`Optional`에도 `map`을 제공하나보네요! 배워갑니다~

2022-09-05 09:57 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +    schedulerService.scheduleTask(task, date);
생각지도 못하고 넘어갈뻔 했네요 .. 

**Runnable안에서 DI를 할 수 없어** `seminarAttendanceRepository`의 값을 제대로 받아오지 못하는 문제가 있었는데 찾아보니 **Runnable을 Bean으로 등록**해서 사용하는 방법도 존재하네요!

`Bean`으로 등록되면 DI가 정상적으로 이루어진다고 합니다.

조금 더 고민해서 수정해보도록 할께요 감사합니다 👍

2022-09-05 09:59 UTC, woo-chang commented on src/main/java/keeper/project/homepage/repository/clerk/SeminarRepository.java
> +      @Param("now") LocalDateTime now);
`Jpa` 메서드를 사용할 때 **인자가 3개 이상인 경우** 이름이 매우 길어지는 상황이 발생하는 것을 직접 작성하면서 느끼게 되었습니다.

그래서 인자가 3개 이상인 경우 위와 같이 직접 쿼리를 작성하고 원하는 메서드명으로 작성하는 것이 가독성이 높아지는 것을 확인할 수 있었습니다.!

2022-09-05 10:00 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +        CustomSeminarAttendanceNotFoundException::new);
으아악 수정하겠습니다 ㅎㅎ

2022-09-05 10:01 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    return status.equals(BEFORE_ATTENDANCE.getType()) && attendanceTime.compareTo(deadline) <= 0;
`LocalDateTime`의 값을 보게 되었을 때 밀리 단위의 값까지 나와서 초까지 비교하기 위해 패턴을 지정하는 것이 필요하다 생각했었는데

비교할 수 있는 메서드를 제공한다면 당연히 그걸 쓰는게 맞다고 생각합니다 .. !

2022-09-05 10:02 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    if (userAttendanceCode.compareTo(seminar.getAttendanceCode()) != 0) {
**비교 비교** 생각하다보니 `compare`만 떠올랐는데 `equals`가 더 적절합니다 .. !

2022-09-05 10:05 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    } else if (attendanceTime.compareTo(latenessDeadLine) <= 0) {
**출석 인정 시간 <= 출석 시간 <= 지각 인정 시간**을 의미합니다!

2022-09-05 10:06 UTC, woo-chang commented on src/main/java/keeper/project/homepage/repository/clerk/SeminarAttendanceRepository.java
> +
제가 사용한 메서드가 아니라 저도 의아했던 부분이였는데 저도 고치는 것이 좋아보입니다!

2022-09-05 10:07 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/controller/clerk/SeminarController.java
> +
조금 더 `REST`를 잘 들어낼 수 있는 `URI`로 변경해보겠습니다!

2022-09-05 10:09 UTC, woo-chang commented on src/main/java/keeper/project/homepage/user/dto/clerk/request/AttendanceCheckRequestDto.java
> +  private LocalDateTime attendanceTime;
출석을 누른 시점을 정확하게 비교하기 위해 클라이언트로부터 받아온다는 생각을 가졌는데 그런 가능성이 존재하네요!

서버로 요청이 들어오는 시간 오차를 감수하더라도 서버에서 시간을 생성하는 것이 좋아보입니다 👍

2022-09-05 10:11 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminMeritService.java
> +     */
SecurityContext의 내용이 존재하지 않기에 지금의 메서드로는 오류가 발생합니다 ㅜ

해당 메서드를 두루 사용하기 위해서는 `DB`에서 조회하거나 `processAttendance` 이전에 `giver`가 조회되는 방식으로 변경되어야 할 것 같습니다!

2022-09-05 10:12 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
> +  public void processAttendance(SeminarAttendanceEntity attendance,
제거하도록 하겠습니당

2022-09-05 10:18 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminMeritService.java
> +     */
@JeonghakLee 이 부분은 혹시 수정 부탁드려도 괜찮을까요?

`processAttendance` 메서드에서 출석 상태만 변경하고 출석 시간은 변경되지 않았던 것 같은데 그 부분에 대해서도 확인부탁드립니다!

2022-09-05 10:27 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/service/clerk/SeminarService.java
> +    } else if (attendanceTime.compareTo(latenessDeadLine) <= 0) {
아하 조건부 메서드로 빼면 더 가독성이 좋을 것 같습니다!

2022-09-05 11:28 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminMeritService.java
> +     */
네 이 부분은 제가 수정하도록 하겠습니다!

2022-09-08 09:23 UTC, woo-chang commented on src/main/java/keeper/project/homepage/admin/service/clerk/AdminSeminarService.java
>        }
처음 테스트 코드 작성 시 **Repository에서 데이터를 불러오지 못하는 문제**가 `DI`가 정상적으로 이루어지지 않아 발생하는 문제라 생각하여 해당 `Task Runnable`을 `Bean`으로 등록하려고 하였습니다.

하지만 해당 Task를 Bean으로 등록하면 다음과 같은 문제가 발생합니다.
- Task 내부에서 AdminSeminarService의 processAttendance 호출이 필요
- AdminSeminarService에서 Task의 메서드를 호출

결론적으로 **순환 참조 문제가 발생**함을 알게 되었습니다.

이를 알고 `DI`에는 문제가 없다 판단하였고 다시 한번 테스트 코드 작성을 해보았고 그 과정에서 `LAZY` 로딩이 진행되는 문제가 발생하였습니다. 그 이유는 Task는 별도의 스레드에서 동작하기에 트랜잭션이 걸리지 않았고 영속성 컨텍스트가 관리하지 못하기에 `LAZY` 로딩을 수행하지 못합니다.

`@Transactional`을 사용하면 메서드 레벌에 선언적 트랜잭션 사용이 가능하지만 부분적으로나 자신 참조에는 트랜잭션을 걸지 못하는 단점이 존재하기에 명시적으로 트랜잭션을 걸 수 있는 `TransactionTemplate`를 사용하였습니다.

이를 통해 트랜잭션 문제는 해결하였으나 아직 하나의 문제가 남아있습니다. 테스트가 별도의 스레드에서 실행되기에 테스트 트랜잭션 커밋 내용에 접근할 수 있도록 해야 생성한 내용을 접근할 수 있고 테스트 코드 상의 롤백이 아닌 Task에서 생성되는 상벌점 로그 롤백에 대한 처리가 남아있습니다. 이는 조금 더 알아본 뒤 천천히 해결해보고자 합니다!

2022-09-09 05:08 UTC, gusah009 approved these changes
따봉 👍
따봉 👍

2022-09-09 05:44 UTC, JeonghakLee approved these changes

2022-09-09 06:50 UTC, merged