Feature/게시글 내 이미지 삽입
KEEPER31337/Homepage-Back pull request #401
Opened 2022-09-07 09:24 UTC by shasuri

게시글 내 이미지 업로드 기능 추가

close #371

첫 PR이라 양질의 리뷰가 필요하단 조언을 듣고 review를 많이 지정했습니다...! 많은 가르침 부탁드립니다!

## 프론트 전달사항
이미지와 postingId를 보내면, 등록된 thumbnail과 file id를 반환합니다.

2022-09-07 09:41 UTC, gusah009 requested changes

2022-09-07 09:41 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +  @PostMapping(value="/newPostingImage", consumes = "multipart/form-data", produces = {
REST API는 `url`과 `method`만으로 Resource의 상태와 동작을 표현할 수 있어야 한다고 생각합니다.

`newPostingImage`는 `Post`라는 `Resource`의 등록을 의미하는 메서드에 `new`라는 키워드가 중복해서 들어간 느낌이 있습니다!

만약 특정 포스트에 이미지를 추가하겠다는 의미를 나타내고 싶다면 아래와 같이 하는 게 좋을 것 같습니다!
`/{postId}/image`

추가로 url에선 **camelCase보다 hyphen을 선호한다고 합니다!** [**스택오버플로우 글**](https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris)

2022-09-07 09:51 UTC, shasuri commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +    public CommonResult uploadPostingImage(
commit 78162a1e60ae5f85dbb1f9930e5046efb98712c6 에서 변경완료 했습니다!

2022-09-07 11:25 UTC, JeonghakLee reviewed
게시글 내 이미지 삽입은 한장만 가능한가요? 
`uploadPostingImage` 메서드만 보면 한장씩 업로드 하는 것 같은데
클라이언트로부터 어떤 과정을 거쳐 이미지 삽입이 이루어지는지 궁금합니다!

2022-09-07 11:25 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/util/dto/ThumbnailFileIdDto.java
> +@Setter
`@Setter`는 사용하지 않으시면 지우셔도 될 것 같습니다!

2022-09-08 06:07 UTC, shasuri commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +  @PostMapping(value="/newPostingImage", consumes = "multipart/form-data", produces = {
commit 986d196d5ceab225e1a86129de8bd4b85f6d43ca에 반영했습니다!

- URL을 `/image/{pid}`로 하는 것과 `/{pid}/image`로 나타내는 것의 의미적인 차이점이 혹시있을까요?

---

- test 작성할 때 겪었던 에러인데, `multipart` 메소드로 `ResultActions`를 구성했는데, 이 경우 docs에 작성하기 위해 `pathParameters`를 사용하면 테스트 실행 시 아래와 같은 오류가 발생합니다. `multipart`와 `@PathVariable`을 동시에 사용하는 방법이 있을까요?

```
java.lang.IllegalArgumentException: urlTemplate not found. If you are using MockMvc did you use RestDocumentationRequestBuilders to build the request?
```

2022-09-08 06:33 UTC, shasuri commented on src/main/java/keeper/project/homepage/util/dto/ThumbnailFileIdDto.java
> +@Setter
게시판에 사용되고 있는 toast ui editor가 사진을 한 장씩 삽입할 수 있어, 한 장을 상정하고 api를 설계했습니다!

issue #371 에도 언급되었듯이, 해당 editor를 사용하면, [addImageBlobHook](https://gareen.tistory.com/49)이  API를 호출하여 이미지와 `postingId`를 백엔드로 전해주고, `fileId`와 `thumbnailId`를 전해 받으면 `<img src="v1/util/thumbnail/{받은 thumbnailId}"\>`와 같이 이미지 태그를 게시글에 넣어주는 방식을 생각하고 있습니다!

2022-09-08 12:09 UTC, shasuri commented on src/main/java/keeper/project/homepage/util/dto/ThumbnailFileIdDto.java
> +package keeper.project.homepage.util.dto;
`user/dto/posting/` 측에 반영해두겠습니다!

2022-09-08 15:35 UTC, shasuri commented on src/main/java/keeper/project/homepage/util/dto/ThumbnailFileIdDto.java
> +package keeper.project.homepage.util.dto;
commit 3ac04b243d41c1c957693bd74a943dfc4491729a
DTO명을 API 용도에 맞춰 변경하였습니다.

2022-09-08 15:45 UTC, shasuri commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +      return responseService.getSuccessSingleResult(thumbnailService.getThumbnailFileId(postingImageEntity));
commit 76d27dc5c4067907eb46f97f11a1f1d5a7215bf7
말씀하신대로 `PostingService`에 메소드를 구현하여 은폐했습니다!

2022-09-09 05:14 UTC, gusah009 requested changes

2022-09-09 05:14 UTC, gusah009 commented on src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
> +        multipart("/v1/post/image/{pid}", postingGeneralTest.getId().toString())
url을 `/post/{pid}/image`는 어떨까요? 복수명사 다음에 특정 id가 나오는 게 직관적일 것 같습니다!

`/v1/post/image/12`는 **12번 이미지**의 느낌이 강하지만 `/v1/post/12/image`는 **12번 포스팅**의 느낌이 강하다고 생각합니다.

아마 여기서 원한건 후자가 아닐까 생각합니다!

2022-09-09 05:14 UTC, gusah009 commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +  @PostMapping(value="/newPostingImage", consumes = "multipart/form-data", produces = {
제가 pull 받아서 테스트를 돌려봤을 땐 잘 되는데 혹시 여전히 그런가요?

2022-09-09 06:09 UTC, shasuri commented on src/test/java/keeper/project/homepage/controller/posting/PostingControllerTest.java
> +        multipart("/v1/post/image/{pid}", postingGeneralTest.getId().toString())
이거 순서 의미가 궁금했었는데... 감사합니다! 재변경 했습니다.
commit 93475ce991ec8e5f7487131cefd10d74e32c9047

2022-09-09 08:10 UTC, shasuri commented on src/main/java/keeper/project/homepage/user/controller/posting/PostingController.java
> +  @PostMapping(value="/newPostingImage", consumes = "multipart/form-data", produces = {
아, 지금 remote에는 `pathParameter`를 없애놔서 버그를 없애놨습니다.
게시물 수정 api 처럼 되어있어요.(`pathVariable`을 요구하지만 문서에는 없는)

2022-09-15 08:11 UTC, woo-chang approved these changes
수고하셨습니다 👍👍 리뷰에 대한 수정이 적절히 이루어진 것 같습니다.

2022-09-16 02:00 UTC, merged