Feature/ctf 카테고리 여러개로 설정되도록 변경
KEEPER31337/Homepage-Back pull request #472
Opened 2022-12-22 14:09 UTC by shkisme

## 연관 issue

close : #471

- #471

## 프론트 전달사항

[ctfAdmin.pdf](https://github.com/KEEPER31337/Homepage-Back/files/10287459/ctfAdmin.pdf)
- CTF 문제 생성
- CTF 문제 오픈
- CTF 문제 닫기
- CTF 문제 삭제
- CTF ADMIN 문제 목록 불러오기

[ctfChallenge.pdf](https://github.com/KEEPER31337/Homepage-Back/files/10287461/ctfChallenge.pdf)

- CTF 문제 목록 조회
- CTF 문제 세부 정보 조회

[ctfTeam.pdf](https://github.com/KEEPER31337/Homepage-Back/files/10287462/ctfTeam.pdf)

- 팀 세부 정보 열람

위 API 문서들은 업데이트 되었습니다!
<hr>

코드 리뷰 해주시면 감사합니다. 🙇‍♀️

2022-12-22 14:30 UTC, woo-chang approved these changes
수고하셨습니다 👏🏻👏🏻

2022-12-22 14:30 UTC, woo-chang commented on src/main/java/keeper/project/homepage/ctf/entity/CtfChallengeHasCtfChallengeCategoryEntity.java
> +@IdClass(CtfChallengeHasCtfChallengeCategoryEntityPK.class) // 정의한 idclass 주입
복합키를 가지는 JPA 엔티티 잘 생성하신 것 같습니다 👍👍

2022-12-22 14:49 UTC, JeonghakLee reviewed
수고하셨습니다!!

2022-12-22 14:49 UTC, JeonghakLee commented on src/main/java/keeper/project/homepage/ctf/dto/CtfChallengeAdminDto.java
> +                toList()))
.collect 한 줄 아래로 내리면 좋을 것 같습니다~

2022-12-22 14:49 UTC, JeonghakLee commented on src/test/java/keeper/project/homepage/ctf/service/CtfAdminServiceTest.java
> +    assertThat(result.getCategory().size()).isEqualTo(1);
size 확인 하는 코드가 중복되는 것 같습니다!

2022-12-22 15:43 UTC, shkisme commented on src/test/java/keeper/project/homepage/ctf/service/CtfAdminServiceTest.java
> +    assertThat(result.getCategory().size()).isEqualTo(1);
반영했습니다!

2022-12-22 15:53 UTC, JeonghakLee approved these changes

2022-12-22 22:11 UTC, gusah009 requested changes
시험기간인데도 너무 고생 많으셨습니다...!!

👏👏👏

2022-12-22 22:11 UTC, gusah009 commented on src/main/java/keeper/project/homepage/ctf/dto/CtfCommonChallengeDto.java
> +            .collect(toList()))
`CtfChallenge`를 상속으로 범위 구분을 한건 제 가장 큰 실수인 것 같습니다... ㅠㅠ 

매번 수정사항이 생길 때 마다 `Admin, Common, Challenge` 3개를 다 바꿔야 하네요 ㅠㅜㅠ

2022-12-22 22:11 UTC, gusah009 commented on src/test/java/keeper/project/homepage/ctf/controller/CtfSpringTestHelper.java
> +      List<CtfChallengeCategoryDto> category,
`CtfChallengeEntity`를 만드는 `generateCtfChallenge`라는 전역적인 코드에 `Dto`가 포함되는건 `Dto`가 테스트코드까지 전파되서 불필요하다고 생각하는데, 기존의 `CtfChallengeCategory` 대신 `Dto`를 새로 사용하신 이유가 있나요?

+ `category` 보다 `categories`가 좋아보입니다! (여기 말고도 다른 곳들도)

2022-12-22 22:11 UTC, gusah009 commented on src/test/java/keeper/project/homepage/ctf/controller/CtfSpringTestHelper.java
> +        fieldWithPath(prefix + ".category[].name").description("문제가 속한 카테고리의 이름"),
위의 커멘트와 중복되긴하는데, `category[]`는 배열이라는걸 바로 알기 힘들 것 같아서 `categories[]`도 좋을 것 같습니다!

2022-12-23 00:01 UTC, shkisme commented on src/test/java/keeper/project/homepage/ctf/controller/CtfSpringTestHelper.java
> +      List<CtfChallengeCategoryDto> category,
`categories`로 변경했습니다! 감사합니다

2022-12-23 00:01 UTC, shkisme commented on src/main/java/keeper/project/homepage/ctf/dto/CtfCommonChallengeDto.java
> +            .collect(toList()))
ㅠㅠ 초금 힘들었어요 😂

2022-12-23 00:03 UTC, shkisme commented on src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
> +      challenge.getCtfChallengeHasCtfChallengeCategoryList().add(save);
`cascade = CascadeType.ALL`, `cascade = CascadeType.PERSIST` 적용시 모두 테스트가 깨져서... ㅠㅠ 이부분 잘 모르겠습니다...

2022-12-23 00:44 UTC, gusah009 commented on src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
> +      challenge.getCtfChallengeHasCtfChallengeCategoryList().add(save);
아하 ㅋㅋㅋㅋㅋㅋ

그럼 일단 Approve하고 차차 공부해봅시당~~!

2022-12-23 00:44 UTC, gusah009 commented on src/main/java/keeper/project/homepage/ctf/service/CtfAdminService.java
> +      challenge.getCtfChallengeHasCtfChallengeCategoryList().add(save);
아하 ㅋㅋㅋㅋㅋㅋ

그럼 일단 Approve하고 차차 공부해봅시당~~!

2022-12-23 00:45 UTC, gusah009 commented on src/main/java/keeper/project/homepage/ctf/dto/CtfCommonChallengeDto.java
> +            .collect(toList()))
얼른 바꿔놓겠습미다!

2022-12-23 00:46 UTC, gusah009 approved these changes
👏👏👏👏👏

2022-12-23 00:50 UTC, shkisme commented
넵!! 감사합니다 😄

2022-12-23 00:51 UTC, merged