Feature/출석 기능 생성
KEEPER31337/Homepage-Back pull request #91
Opened 2022-02-02 05:23 UTC by koty08

2022-02-02 10:08 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/attendance/DateUtils.java
> +}
이건 어디서 가져왔대 굿굿 👍👍👍

2022-02-02 10:08 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
> +      point += 500;
상수는 그 의미가 명확하게 `public static final`로 선언 해주는 게 좋을 것 같애

2022-02-02 21:52 UTC, gusah009 requested changes

2022-02-03 10:11 UTC, gusah009 commented on src/main/java/keeper/project/homepage/dto/attendance/AttendanceDto.java
> +  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "Asia/Seoul")
@koty08 여기 `'T'`는 왜 쓴거야?

2022-02-03 12:10 UTC, koty08 commented on src/main/java/keeper/project/homepage/dto/attendance/AttendanceDto.java
> +  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "Asia/Seoul")
https://ksy93.tistory.com/m/entry/SpringBoot-DateTime-Format

공백 방법으로 하니까 Postman에서는 잘 처리가 되는데 테스트코드에선 잘 안먹어서 일단 중간에 T를 넣어서 처리했습니다.

2022-02-03 12:11 UTC, koty08 commented on src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
> +    for (AttendanceEntity attendanceEntity : attendanceEntities) {
👌

2022-02-03 12:12 UTC, koty08 commented on src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
> +      point += 500;
👌

2022-02-04 02:55 UTC, gusah009 approved these changes
이건 고쳐야될듯

2022-02-04 02:55 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
> +
@koty08 
아래 코드는 악의적으로 이틀 전 날짜를 전달해서 이틀 전 출석을 처리하는 코드야. 오늘 날짜가 아닌데 출석이 인정되면 안되겠지? 프론트에서 시간을 받아오는 건 너무 프론트를 믿는 행위라고 생각해. dto에서 time을 빼거나, 아니면 time을 받아오되, 서버에서 오늘인지 아닌지 처리하는 부분이 필요할 것 같아.

```java
AttendanceDto attendanceDto = AttendanceDto.builder()
    .greetings("hi")
    .ipAddress(ipAddress1)
    .memberId(memberEntity.getId())
    .time(LocalDateTime.now().minusDays(2)).build();
String content = objectMapper.writeValueAsString(attendanceDto);

mockMvc.perform(
    MockMvcRequestBuilders.post("/v1/attend/check").contentType(
        MediaType.APPLICATION_JSON).content(content));
```

2022-02-04 02:55 UTC, gusah009 commented on src/main/java/keeper/project/homepage/service/attendance/AttendanceService.java
> +            .memberId(memberEntity).randomPoint(random.nextInt(100, 1001)).build());
@koty08 
위 코드를 봤을 때, 너가 원하는 건 attendanceRepository에 save할 때, Member의 point 역시 랜덤 포인트가 들어가게 하려고 하는 것 같은데 문제가 2가지 있어.
1. **randomPoint를 직접 집어넣고 있다.**
   - 기존 point에 randomPoint만큼 더하는 것도 아니고, 랜덤 포인트로 갱신되려고 하고 있어. 일단 이게 첫번째 문제야.
2. **위 방식으론 member point가 저장되지 않는다.**
   - 안타깝지만 위 방식으론 JPA에서 Member 저장 처리를 해주지 않아. 따로 `memberRepository.save()`를 불러서 update 시켜야 해. JPA에 대해 조금 더 공부해봐도 좋을 것 같아.
   - 
링크 추천 해 놓을게 ㅎㅎ [이 문제 답 모르면 제발 JPA 쓰지 마세요. 공부를 하거나. feat 서연](https://www.youtube.com/watch?v=brE0tYOV9jQ)

2022-02-07 12:29 UTC, merged